build:
  maxIssues: 0
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1

config:
  validation: true
  warningsAsErrors: false
  excludes: '.*Generated.kt'

processors:
  active: true
  exclude:
    - 'FunctionCountProcessor'
    - 'PropertyCountProcessor'

console-reports:
  active: true

output-reports:
  active: true

style:
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2', '100', '1000']
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreAnnotation: true

  WildcardImport:
    active: true

  ForbiddenComment:
    active: true
    comments: [ 'FIXME:' ]

  ReturnCount:
    active: false

  # Desabilitar explicitamente a regra MaxLineLength padrão
  MaxLineLength:
    active: false

naming:
  FunctionNaming:
    active: true
    functionPattern: '^[a-z][A-Za-z0-9]*$'
    ignoreAnnotated: [ 'Test', 'Composable' ]

  VariableNaming:
    active: true
    variablePattern: '^[a-z][A-Za-z0-9]*$'

  TopLevelPropertyNaming:
    active: false

  ClassNaming:
    active: true
    classPattern: '^[A-Z][a-zA-Z0-9]*$'

complexity:
  LongMethod:
    active: true
    threshold: 60

  LargeClass:
    active: false

  TooManyFunctions:
    active: false

  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 6
    ignoreDefaultParameters: true

  ComplexCondition:
    active: true
    threshold: 5

performance:
  SpreadOperator:
    active: false  # nem sempre é um problema

potential-bugs:
  active: true

  UnsafeCallOnNullableType:
    active: true

formatting:
  active: true
  autoCorrect: true
  
  # Indentation
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 4
    
  # Desabilitar MaximumLineLength - deixar outras regras quebrarem as linhas
  MaximumLineLength:
    active: false

  # Import ordering
  ImportOrdering:
    active: true
    autoCorrect: true
    
  # No wildcard imports
  NoWildcardImports:
    active: true
    autoCorrect: true
    
  # Trailing comma
  TrailingCommaOnCallSite:
    active: true
    autoCorrect: true
    useTrailingCommaOnCallSite: true
    
  TrailingCommaOnDeclarationSite:
    active: true
    autoCorrect: true
    useTrailingCommaOnDeclarationSite: true
    
  # Spacing
  SpacingBetweenPackageAndImports:
    active: true
    autoCorrect: true
    
  SpacingAroundColon:
    active: true
    autoCorrect: true
    
  SpacingAroundComma:
    active: true
    autoCorrect: true
    
  SpacingAroundCurly:
    active: true
    autoCorrect: true
    
  SpacingAroundKeyword:
    active: true
    autoCorrect: true
    
  SpacingAroundOperators:
    active: true
    autoCorrect: true
    
  SpacingAroundParens:
    active: true
    autoCorrect: true
    
  SpacingAroundRangeOperator:
    active: true
    autoCorrect: true
    
  # Parameter and argument list formatting - configurações mais agressivas
  ParameterListWrapping:
    active: true
    autoCorrect: true
    maxLineLength: 100  # Mais agressivo para forçar quebras

  ArgumentListWrapping:
    active: true
    autoCorrect: true
    maxLineLength: 100  # Mais agressivo para forçar quebras

  # Chain wrapping
  ChainWrapping:
    active: true
    autoCorrect: true
    
  # Annotation formatting
  AnnotationOnSeparateLine:
    active: true
    autoCorrect: true
    
  # Final newline
  FinalNewline:
    active: true
    autoCorrect: true
    insertFinalNewLine: true
    
  # No blank lines before closing brace
  NoBlankLineBeforeRbrace:
    active: true
    autoCorrect: true
    
  # No consecutive blank lines
  NoConsecutiveBlankLines:
    active: true
    autoCorrect: true
    
  # No empty class body
  NoEmptyClassBody:
    active: true
    autoCorrect: true
    
  # No line break after else
  NoLineBreakAfterElse:
    active: true
    autoCorrect: true
    
  # No line break before assignment
  NoLineBreakBeforeAssignment:
    active: true
    autoCorrect: true
    
  # No multi spaces
  NoMultipleSpaces:
    active: true
    autoCorrect: true
    
  # No semicolons
  NoSemicolons:
    active: true
    autoCorrect: true
    
  # No trailing spaces
  NoTrailingSpaces:
    active: true
    autoCorrect: true
    
  # No unit return
  NoUnitReturn:
    active: true
    autoCorrect: true
    
  # No unused imports
  NoUnusedImports:
    active: true
    autoCorrect: true
    
  # String template
  StringTemplate:
    active: true
    autoCorrect: true
